### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by surajverma2587** [AOsman0/library-of-knowledge#1]
### Tasks

- [x] Add css framework
- [x] add html, css, js files
- [x] add momentJS
- [x] add jquery
- [x] add fonts
- [x] added color scheme
- [x] added icons link
